-- H2 2.2.224;
;             
CREATE USER IF NOT EXISTS "SA" SALT '6349adb1faa47199' HASH '92dd8ba6f9f1b9e2389fa6a9cc1f48496576d50b21c612c8655313f617c453e0' ADMIN;         
CREATE SEQUENCE "PUBLIC"."PHONE_SEQ" START WITH 1 INCREMENT BY 50;            
CREATE MEMORY TABLE "PUBLIC"."PHONE"(
    "ID" BIGINT NOT NULL,
    "CITY_CODE" CHARACTER VARYING(255),
    "COUNTRY_CODE" CHARACTER VARYING(255),
    "NUMBER" CHARACTER VARYING(255)
);
ALTER TABLE "PUBLIC"."PHONE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" PRIMARY KEY("ID");        
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PHONE;   
CREATE MEMORY TABLE "PUBLIC"."USER_PROFILE"(
    "IS_ACTIVE" BOOLEAN NOT NULL,
    "CREATED" TIMESTAMP(6),
    "LAST_LOGIN" TIMESTAMP(6),
    "MODIFIED" TIMESTAMP(6),
    "ID" UUID NOT NULL,
    "EMAIL" CHARACTER VARYING(255),
    "NAME" CHARACTER VARYING(255),
    "PASSWORD" CHARACTER VARYING(255),
    "TOKEN" CHARACTER VARYING(255)
);  
ALTER TABLE "PUBLIC"."USER_PROFILE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_C" PRIMARY KEY("ID"); 
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.USER_PROFILE;            
CREATE MEMORY TABLE "PUBLIC"."USER_PROFILE_PHONES"(
    "PHONES_ID" BIGINT NOT NULL,
    "USER_PROFILE_ID" UUID NOT NULL
);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.USER_PROFILE_PHONES;     
ALTER TABLE "PUBLIC"."USER_PROFILE_PHONES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_48" UNIQUE("PHONES_ID");       
ALTER TABLE "PUBLIC"."USER_PROFILE_PHONES" ADD CONSTRAINT "PUBLIC"."FKC8TPXLRY2NH5VE78QVD12CIS" FOREIGN KEY("USER_PROFILE_ID") REFERENCES "PUBLIC"."USER_PROFILE"("ID") NOCHECK;              
ALTER TABLE "PUBLIC"."USER_PROFILE_PHONES" ADD CONSTRAINT "PUBLIC"."FKRX1G8LKLVJRIRR8K1Q967C40S" FOREIGN KEY("PHONES_ID") REFERENCES "PUBLIC"."PHONE"("ID") NOCHECK;          
